version: "3"
services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: 0.0.0.0
    ports:
      - "3307:3306"
  app:
    tty: true
    stdin_open: true
    depends_on:
      - "db"
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: pearson_media_center
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
    volumes:
      - ".:/app"
volumes:
  db:
